### PR TITLE
Fix missing tutum/curl image

### PR DESCRIPTION
**Pull request by herbertgoto**
*Issue #, if available:*
tutum/curl image is missing.

*Description of changes:*
Change that image for a public alpine/curler managed by me.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cgchinmay** [comment]
lgtm

**Review by cgchinmay — APPROVED** [review]

**Comment by Y0Username** [comment]
It's weird how it has 16 commits

**Comment by Y0Username** [comment]
Could you make sure your fork is sync'ed and please raise the PRs against the branch `main` that is the default branch for this repo, thanks :)

**Comment by cgchinmay** [comment]
@herbertgoto squash your commits, that would help :)

**Pull request closed without merging**
