### PR TITLE
Update Envoy image references to v1.11.1

### PR DESCRIPTION
**Pull request by bcelenza**
*Issue #, if available:*

https://github.com/aws/aws-app-mesh-roadmap/issues/92

*Description of changes:*

Update all references to the official Envoy image to 1.11.1.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by efe-selcuk** [comment]
- Looks like `examples/apps/colorapp/README.md` has some references to 1.9, can you update those too?
- `walkthroughs/howto-servicediscovery-cloudmap/app.yaml` has references to 1.9 in his own repository. Need to follow up with @subfuzion to get that image update (or just share this one if possible).

**Comment by lavignes** [comment]
@efe-selcuk We should be able to just use 1.11.1.0 in the cloudmap howto.

**Comment by lavignes** [comment]
https://github.com/aws/aws-app-mesh-examples/search?q=%22aws-appmesh-envoy%22&unscoped_q=%22aws-appmesh-envoy%22

**Comment by lavignes** [comment]
@efe-selcuk We need to remove the references to @subfuzion's ECR repros. Demos should have customers build/upload to a personal ECR repository.

**Comment by lavignes** [comment]
Added followup for the other external iamges: #191

**Comment by bcelenza** [comment]
@efe-selcuk updated the colorapp readme

**Pull request merged**
