### PR TITLE
PR for Issue #484

### PR DESCRIPTION
**Pull request by codesometech**
*Issue #, if available:*
https://github.com/aws/aws-app-mesh-examples/issues/484

*Description of changes:*
Updated the path to envoy binary in custom envoy script

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by suniltheta — CHANGES_REQUESTED** [review]
https://github.com/aws/aws-app-mesh-examples/blob/main/walkthroughs/howto-mutual-tls-file-provided-by-acm/src/customEnvoyImage/entryPoint.sh#L24 Can this file be fixed as well?

**Comment by codesometech** [comment]
> https://github.com/aws/aws-app-mesh-examples/blob/main/walkthroughs/howto-mutual-tls-file-provided-by-acm/src/customEnvoyImage/entryPoint.sh#L24 Can this file be fixed as well?
That's fixed as part of https://github.com/aws/aws-app-mesh-examples/pull/485

**Comment by suniltheta** [comment]
I closed the other one. let all the changes be in a single commit.

**Comment by codesometech** [comment]
> I closed the other one. let all the changes be in a single commit.

Done.

**Review by suniltheta — APPROVED** [review]
LGMT, thanks

**Review by suniltheta — APPROVED** [review]

**Review by liubnu — APPROVED** [review]

**Pull request merged**
