### PR TITLE
Interactive demo move

### PR DESCRIPTION
**Pull request by jasonrichardsmith**
*Issue #, if available:*
https://github.com/aws/aws-app-mesh-inject/issues/36

*Description of changes:*
This moves the interactive demo from the sidecar injection repo to this repo, and fixes some bugs related to sidecar naming conventions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by efe-selcuk** [comment]
Could the resources be changed to cloudformation like our colorapp? It'll also fix any flakiness in the setup/teardown from eventual consistency in the APIs.

**Comment by jasonrichardsmith** [comment]
Sure, this was written before any of that was available, so I had not added it yet.

**Comment by bcelenza** [comment]
High level comments:
1. Could we name the example directory more specifically for what this demo is showcasing?
2. Could we add some information in the top-level readme on what examples exist and which one to choose depending on interest? This has a lot of overlap with https://github.com/aws/aws-app-mesh-examples/pull/126 and I'm worried about that being confusing.

**Comment by jasonrichardsmith** [comment]
@bcelenza I can't speak to #126 but I wrote this particular demo to demonstrate several things, such as:
- circuit breaking
- rate limiting
- egress
- traffic shifting
- mirroring
- header based routing
- timeout rules
- prometheus scraping

**Comment by jasonrichardsmith** [comment]
Thanks for the feedback.  I am on holiday right now, when I return I will work on adding CF and CRD options.  I would prefer to give the user the option of all because it gives a full insight of what is happening.

**Pull request closed without merging**
